### ISSUE TITLE
chmod in buildEjectCommand is failing on windows

### ISSUE THREAD

**Issue by giraud** [jordwalke/esy#44]
When I run `./node_modules/esy/.bin/esy.js build-eject` in windows (msys), I got the following error:

```ejecting: _esy\findlib.conf.in
ejecting: _esy\sandbox.sb.in
ejecting: _esy\bin\render-env
fs.js:1154
  return binding.chmod(pathModule._makeLong(path), modeNum(mode));
                 ^

TypeError: mode must be an integer
    at TypeError (native)
    at Object.fs.chmodSync (fs.js:1154:18)
    at emitFile (C:\MinGW\msys\1.0\home\giraud\esy-ocaml-project\node_modules\esy\lib\esyBuildEjectCommand.js:50:10)
    at buildEjectCommand (C:\MinGW\msys\1.0\home\giraud\esy-ocaml-project\node_modules\esy\lib\esyBuildEjectCommand.js:324:3)
    at build-eject (C:\MinGW\msys\1.0\home\giraud\esy-ocaml-project\node_modules\esy\.bin\esy.js:145:5)
    at Object.<anonymous> (C:\MinGW\msys\1.0\home\giraud\esy-ocaml-project\node_modules\esy\.bin\esy.js:166:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

the `fs.constants.S_IRWXU` is undefined on my host.

**Comment by jordwalke** [comment]
Are you using msys or msys2?

**Comment by jordwalke** [comment]
This might have nothing to do with msys and it could be more related to node on windows:
It seems like some values will work and others won't.

https://github.com/nodejs/node-v0.x-archive/issues/4812

**Comment by giraud** [comment]
I used msys. But after your comment I tested it again with msys2 and I got the same result

**Comment by jordwalke** [comment]
Interestingly, I saw this error in non-windows builds (Node v 6.1 or earlier). Curious which version of node you used.
