### ISSUE TITLE
When "make"ing submodules, errors occur.

### ISSUE THREAD

**Issue by jordwalke** [jordwalke/esy#48]
1. We need to update the docs to have people do `git clone --recursive` if cloning esy (I think).
2. Update the docs to indicate that people need to `cd esy/opam-packages-conversion/`.
3. I'm seeing a bunch of errors when running `make`

Here's some examples:
```
Traceback (most recent call last):
  File "./bin/build-package", line 79, in <module>
    build_package(name, *versions)
  File "./bin/build-package", line 62, in build_package
    os.path.join(package_dir, name + '.' + version)
  File "/Users/me/github/esy/opam-packages-conversion/bin/lib.py", line 20, in generate_package_json
    package_url = re.search(r"(archive:\s*|http:\s*|src:\s*)\"(.*)\"", content).group(2)
AttributeError: 'NoneType' object has no attribute 'group'
*** building ppx_type_conv
```

And:

```
Traceback (most recent call last):
  File "./bin/build-package", line 79, in <module>
    build_package(name, *versions)
  File "./bin/build-package", line 62, in build_package
    os.path.join(package_dir, name + '.' + version)
  File "/Users/me/github/esy/opam-packages-conversion/bin/lib.py", line 243, in generate_package_json
    buildFlatList(d["substs"]), breakList(d["build"]) + breakList(d["install"]))
  File "/Users/me/github/esy/opam-packages-conversion/bin/lib.py", line 191, in createPostInstallCommand
    return [unescapeBuiltinVariables(cmd) for cmd in build]
  File "/Users/me/github/esy/opam-packages-conversion/bin/lib.py", line 158, in unescapeBuiltinVariables
    return re.sub(r"%\{(.*?)\}%", escape, s)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/Users/me/github/esy/opam-packages-conversion/bin/lib.py", line 157, in escape
    raise Exception("Cannot expand variable %s" % var)
Exception: Cannot expand variable share
```

**Comment by jordwalke** [comment]
So, I'm pretty sure that lib.py on line 20 should be changed to this regex:

`                package_url = re.search(r"(archive\s*:\s*|https\s*:\s*|http\s*:\s*|src\s*:\s*)\"(.*)\"", content).group(2)
`
(Allowing arbitrary space before the colon), and also allowing `https` urls.

That doesn't fix everything though.

**Comment by jordwalke** [comment]
Here's some more errors which are strange when running `make` from within the submodules:

```
*** building biniou
fatal: ref HEAD is not a symbolic ref
Traceback (most recent call last):
  File "./bin/build-package", line 76, in <module>
    build_package_version_from_git_repo(name, ref, orig_ref)
  File "./bin/build-package", line 45, in build_package_version_from_git_repo
    branch_name = capture('git symbolic-ref --short HEAD')
  File "./bin/build-package", line 42, in capture
    return subprocess.check_output(cmd % args, cwd=repo_dir, shell=True)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'git symbolic-ref --short HEAD' returned non-zero exit status 128
*** building base-threads
*** building ./forks/camlp4
fatal: ref HEAD is not a symbolic ref
Traceback (most recent call last):
  File "./bin/build-package", line 76, in <module>
    build_package_version_from_git_repo(name, ref, orig_ref)
  File "./bin/build-package", line 45, in build_package_version_from_git_repo
    branch_name = capture('git symbolic-ref --short HEAD')
  File "./bin/build-package", line 42, in capture
    return subprocess.check_output(cmd % args, cwd=repo_dir, shell=True)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'git symbolic-ref --short HEAD' returned non-zero exit status 128

```

**Comment by jordwalke** [comment]
We also had to change this line of `installCommand/index.js` (when using `esy` locally in a clone of `esy`):

```
const OPAM_METADATA_STORE = path.join(__dirname, '..', '..', 'opam-packages-conversion', 'output');
```

Note the extra `..`.

**Comment by jordwalke** [comment]
We're probably just doing something terribly wrong. We're not sure how to set everything up so things could just be in a broken state. We likely just need good docs about how to get everything building correctly.

Is this correct?

```
git clone link-to-esy
npm install
git submodule init
git submodule update
make  convert-opam-packages
```

**Comment by yutongp** [comment]
I see bunch of python errors when I run `make convert-opam-pakcages` like:
```
*** building xe-unikernel-upload
Traceback (most recent call last):
  File "./bin/build-package", line 78, in <module>
    build_package(name, *versions)
  File "./bin/build-package", line 61, in build_package
    os.path.join(package_dir, name + '.' + version)
  File "/Users/yutongpei/Code/reason/esy/opam-packages-conversion/bin/lib.py", line 243, in generate_package_json
    buildFlatList(d["substs"]), breakList(d["build"]) + breakList(d["install"]))
  File "/Users/yutongpei/Code/reason/esy/opam-packages-conversion/bin/lib.py", line 191, in createPostInstallCommand
    return [unescapeBuiltinVariables(cmd) for cmd in build]
  File "/Users/yutongpei/Code/reason/esy/opam-packages-conversion/bin/lib.py", line 158, in unescapeBuiltinVariables
    return re.sub(r"%\{(.*?)\}%", escape, s)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/Users/yutongpei/Code/reason/esy/opam-packages-conversion/bin/lib.py", line 157, in escape
    raise Exception("Cannot expand variable %s" % var)
```
Probably same issue

**Comment by jordwalke** [comment]
Seems to no longer be an issue.

**Comment by andreypopp** [comment]
Errors are still present we just silence them for now — if anyone wants to investigate:
```
cd opam-packages-conversion
make convert
```
