### ISSUE TITLE
I can't build esy off of the master branch as of commit id: 5a705f93c3f10d4017cac85d3ae929a01ff28dd9

### ISSUE THREAD

**Issue by omefire** [jordwalke/esy#92]
I am getting a build failure when I run `make convert-opam-packages`:

```
Traceback (most recent call last):
  File "./bin/build-package", line 78, in <module>
    build_package(name, *versions)
  File "./bin/build-package", line 61, in build_package
    os.path.join(package_dir, name + '.' + version)
  File "/Users/omefire/Projects/esy/opam-packages-conversion/bin/lib.py", line 299, in generate_package_json
    npm_range = opamRangeToNpmRange(range)
  File "/Users/omefire/Projects/esy/opam-packages-conversion/bin/lib.py", line 245, in opamRangeToNpmRange
    assert ("|" not in range)
AssertionError
make[1]: *** [convert] Error 1
omefire-Mac:esy omefire$ 
```

Can anyone point me in the right direction ? My bash fu is really low, :)

**Comment by andreypopp** [comment]
Hi @omefire, that's expected now — some packages from opam are failed to convert to Esy's `package.json` but overall things should work.

**Comment by omefire** [comment]
Thanks @andreypopp. I'll ignore the errors then and go ahead and just use the built artifact (./bin/esy build) just like nothing happened.

**Comment by andreypopp** [comment]
@omefire right.

**Comment by omefire** [comment]
Closing this issue then.
